 # HTTP (Tomcat) port
server:
  port: 8585
  
#Configuracion de acceso a base de datos
spring:
  datasource:
    url: jdbc:mysql://10.1.2.35:3306/herramientas
    username: jarodrig
    password: jarodrig
    driverClassName: com.mysql.jdbc.Driver

#Scripts de gestion para encuestas
query:
  encuesta:
    lista: SELECT * FROM herramientas.encuestas;
    registra: INSERT INTO herramientas.encuestas VALUES (NULL,?,?,?,?,?,?,?,?,?);
  preguntas:
    listaPreguntas: SELECT * FROM `herramientas`.preguntas p WHERE p.idEncuesta =?;
    listaRespuestas: SELECT r.`idRespuesta`,r.`respuesta`, r.`estatus`, 0 AS total FROM  `herramientas`.`respuestas` r WHERE r.`idPregunta` = ?;
    registraPreguntas: INSERT INTO herramientas.preguntas (pregunta,tipoPregunta,urlImagen,idEncuesta) VALUES (?,?,?,?);
    registraRespuestas: INSERT INTO `herramientas`.`respuestas` VALUES (NULL,?,?,?);
    registraFormularioContestado: INSERT INTO `herramientas`.`form_contestados` VALUES (NULL, ?, ?, ?, ?, ?, ?);
    listaAllFormularioContestado: SELECT r.`idRespuesta`, r.`respuesta`,r.`estatus`, COUNT(r.`idRespuesta`) AS total FROM  `herramientas`.`form_contestados` fc INNER JOIN `herramientas`.`respuestas` AS r ON r.`idRespuesta` = fc.`idRespuesta` WHERE r.`idPregunta` = ? GROUP BY  r.`idRespuesta`;
    listaAllRespuestasContestadas: SELECT  0,fc.texto,FALSE,0 AS total  FROM  `herramientas`.`form_contestados` fc WHERE fc.`idPregunta` = ? ;
