 # HTTP (Tomcat) port
server:
  port: 8585
  
#Configuracion de acceso a base de datos
spring:
  datasource:
    url: jdbc:mysql://10.1.2.35:3306/herramientas
    username: jarodrig
    password: jarodrig
    driverClassName: com.mysql.jdbc.Driver

#Scripts de gestion para encuestas
query:
  encueta:
    lista: SELECT * FROM herramientas.encuestas;
    registra: INSERT INTO herramientas.encuestas VALUES (NULL,?,?,?,?,?,?,?,?);
